### PR TITLE
Remove M2-mode.el

### PR DESCRIPTION
**Pull request by d-torrance**
We remove `M2-mode.el`.  Its content was removed in 2003!  See 4ecb0aea56b5eb2f62b6f2150978b50d9deba03b.

### CODE REVIEW

**Comment by mahrud** [comment]
Looking on my computer, I see loads of `X-mode.el` files and occasionally `X.el` in addition. I figured the convention was to put major modes in `X-mode.el` and if there is more (e.g. `send-to-program`) that could go in `X.el`. I don't know if this is formal though, and I don't have strong feelings about it.

**Comment by d-torrance** [comment]
`M2` is the "feature" provided by `M2.el` (since `M2.el` ends with `(provide 'M2)` and it can be loaded with `(require 'M2)`).  According to the https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html:

> Features are normally named after the files that provide them

Most of the `X-mode.el` files on my system end with `(require 'X-mode)`.

**Comment by mahrud** [comment]
Is it just a matter of picking which of M2 or M2-mode are the main feature? Would it be more proper if they were split?

**Comment by d-torrance** [comment]
I don't think we'd need to split it.  Other interpreted languages like Python and Octave that have at least two major modes in Emacs (one for editing code and one for interacting with the REPL) are set up just like ours using one file/feature.

**Comment by d-torrance** [comment]
I'm not sure if I'm happy with it.  I didn't realize initially that `(require 'M2-mode)` was mentioned in the README.  I've changed that in [4c617cd](https://github.com/Macaulay2/M2-emacs/pull/62/commits/4c617cd36a46219ce2522618db64dde8b8023500), but if anyone has that in their config, this would break it.

**Comment by mahrud** [comment]
For what it's worth, my goal in separating this repository away was to make it possible to use M2 syntax highlighting even if M2 isn't installed, so I saw M2-mode as the main "feature" here and send-to-program as a nice utility which could even be separated. (In fact, I've used it for other repls by simply changing the program to like python several times).

**Comment by d-torrance** [comment]
> Could one of M2 or M2-mode be added as an alias so nobody's system breaks?

Unless a second optional  argument with a specific filename is passed to `require`, it will use the feature name to figure out the file to load, e.g., `(require 'M2-mode)` will look for `M2-mode.el`.

I'm going to close this.

**Pull request closed without merging**
