### PR TITLE
Updates for version 1.23

### PR DESCRIPTION
**Pull request by d-torrance**
We update the generated symbols and documentation files and also update the version number of the package to match M2's.

### CODE REVIEW

**Comment by mahrud** [comment]
Why are the commits on this branch on top of changes from back in May 2023 rather than the `main` branch?

**Comment by d-torrance** [comment]
Good question!   No idea what I did.  Thanks for catching this.  I'll rebase it here in a moment...

**Comment by d-torrance** [comment]
A strange consequence of merging this linearly is that GitHub apparently forgot which commits belonged to this PR!  I don't think that's very desirable for historical purposes.

**Comment by mahrud** [comment]
Agreed, though I intentionally wanted to test it on this PR since it seemed least likely to be look up later or need to be reverted.

**Pull request merged**
